version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu
environment:
  GITHUB_TOKEN:
    secure: DlTcKUdz2lpvWvTjhiPlc0kLAcZUPCkXgkmoREbOnv3XOwEq7ubTR+DrN6lFeEXs
install:
- sh: npm install
cache: node_modules
build: off
test_script:
- sh: npm run lint & npm test